## Import Libraries

In [1]:
import pandas as pd
import numpy as np

## Load Dataset

In [2]:
file_path = "../datasets/raw_datasets/Crimes_-_2001_to_Present_20260427.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully ✅")

Dataset loaded successfully ✅

## Exploration

In [3]:
df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,14170481,JK221949,04/18/2026 12:00:00 AM,062XX N OAKLEY AVE,0560,ASSAULT,SIMPLE,APARTMENT,False,False,...,50.0,2.0,08A,1159851.0,1941463.0,2026,04/25/2026 03:43:40 PM,41.995090,-87.687348,"(41.995089758, -87.687347786)"
1,14171093,JK222668,04/18/2026 12:00:00 AM,052XX W BLOOMINGDALE AVE,0710,THEFT,THEFT FROM MOTOR VEHICLE,STREET,False,False,...,37.0,25.0,06,1141324.0,1911471.0,2026,04/25/2026 03:43:40 PM,41.913152,-87.756243,"(41.913152281, -87.756242665)"
2,14175980,JK228905,04/18/2026 12:00:00 AM,011XX W ERIE ST,1581,SEX OFFENSE,NON-CONSENSUAL DISSEMINATION OF PRIVATE SEXUAL...,RESIDENCE,False,False,...,27.0,24.0,17,1168519.0,1904430.0,2026,04/25/2026 03:43:40 PM,41.893286,-87.656538,"(41.893285756, -87.656538409)"
3,14170651,JK222150,04/18/2026 12:00:00 AM,001XX E WALTON PL,0810,THEFT,OVER $500,HOTEL / MOTEL,False,False,...,2.0,8.0,06,1177614.0,1906959.0,2026,04/25/2026 03:43:40 PM,41.900024,-87.623059,"(41.90002373, -87.62305924)"
4,14170751,JK222275,04/18/2026 12:00:00 AM,077XX S SOUTH SHORE DR,1310,CRIMINAL DAMAGE,TO PROPERTY,APARTMENT,False,False,...,7.0,43.0,14,1197197.0,1854817.0,2026,04/25/2026 03:43:40 PM,41.756477,-87.552872,"(41.756476826, -87.552872024)"

In [4]:
df.tail()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
8539232,4768442,HM381863,01/01/2001 12:00:00 AM,048XX S KENWOOD AVE,1753,OFFENSE INVOLVING CHILDREN,SEX ASSLT OF CHILD BY FAM MBR,RESIDENCE,False,False,...,4.0,39.0,02,1185896.0,1873229.0,2001,06/08/2006 04:09:24 AM,41.807275,-87.593707,"(41.807274768, -87.593706931)"
8539233,10473864,HZ213356,01/01/2001 12:00:00 AM,012XX S DAMEN AVE,1582,OFFENSE INVOLVING CHILDREN,CHILD PORNOGRAPHY,OTHER,False,False,...,2.0,28.0,17,NaN,NaN,2001,04/09/2016 03:47:49 PM,NaN,NaN,NaN
8539234,1322043,G003560,01/01/2001 12:00:00 AM,061XX S ARTESIAN AV,1310,CRIMINAL DAMAGE,TO PROPERTY,RESIDENCE,False,False,...,NaN,NaN,14,1161130.0,1863925.0,2001,08/17/2015 03:03:40 PM,41.782292,-87.684799,"(41.782292325, -87.684798685)"
8539235,7277327,HR690758,01/01/2001 12:00:00 AM,023XX S SACRAMENTO AVE,0841,THEFT,FINANCIAL ID THEFT:$300 &UNDER,RESIDENCE,False,False,...,12.0,30.0,06,1156774.0,1888069.0,2001,01/01/2010 01:04:39 AM,41.848636,-87.700117,"(41.848635623, -87.700116823)"
8539236,3180127,HK185693,01/01/2001 12:00:00 AM,078XX S LANGLEY AVE,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,...,6.0,69.0,06,1182216.0,1853077.0,2001,03/31/2006 10:03:38 PM,41.752062,-87.607828,"(41.752061911, -87.607827503)"

In [5]:
# Shape of dataset
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 8539237
Columns: 22

In [6]:
df.columns

Index(['ID', 'Case Number', 'Date', 'Block', 'IUCR', 'Primary Type',
       'Description', 'Location Description', 'Arrest', 'Domestic', 'Beat',
       'District', 'Ward', 'Community Area', 'FBI Code', 'X Coordinate',
       'Y Coordinate', 'Year', 'Updated On', 'Latitude', 'Longitude',
       'Location'],
      dtype='object')

In [7]:
df.dtypes

ID                        int64
Case Number              object
Date                     object
Block                    object
IUCR                     object
Primary Type             object
Description              object
Location Description     object
Arrest                     bool
Domestic                   bool
Beat                      int64
District                float64
Ward                    float64
Community Area          float64
FBI Code                 object
X Coordinate            float64
Y Coordinate            float64
Year                      int64
Updated On               object
Latitude                float64
Longitude               float64
Location                 object
dtype: object

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8539237 entries, 0 to 8539236
Data columns (total 22 columns):
 #   Column                Dtype
---  ------                -----
 0   ID                    int64
 1   Case Number           object
 2   Date                  object
 3   Block                 object
 4   IUCR                  object
 5   Primary Type          object
 6   Description           object
 7   Location Description  object
 8   Arrest                bool
 9   Domestic              bool
 10  Beat                  int64
 11  District              float64
 12  Ward                  float64
 13  Community Area        float64
 14  FBI Code              object
 15  X Coordinate          float64
 16  Y Coordinate          float64
 17  Year                  int64
 18  Updated On            object
 19  Latitude              float64
 20  Longitude             float64
 21  Location              object
dtypes: bool(2), float64(7), int64(3), object(10)
memory usage: 1.3+ GB

In [9]:
df.describe()

,ID,Beat,District,Ward,Community Area,X Coordinate,Y Coordinate,Year,Latitude,Longitude
count,8.539237e+06,8.539237e+06,8.539190e+06,7.924422e+06,7.925511e+06,8.442794e+06,8.442794e+06,8.539237e+06,8.442794e+06,8.442794e+06
mean,7.605256e+06,1.183040e+03,1.129539e+01,2.278849e+01,3.736253e+01,1.164670e+06,1.885931e+06,2.011203e+03,4.184259e+01,-8.767123e+01
std,3.832166e+06,7.038079e+02,6.965237e+00,1.385999e+01,2.154614e+01,1.694295e+04,3.241650e+04,7.223543e+00,8.918815e-02,6.140238e-02
min,6.340000e+02,1.110000e+02,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.001000e+03,3.661945e+01,-9.168657e+01
25%,4.122025e+06,6.210000e+02,6.000000e+00,1.000000e+01,2.300000e+01,1.153093e+06,1.859225e+06,2.005000e+03,4.176901e+01,-8.771324e+01
50%,7.602860e+06,1.034000e+03,1.000000e+01,2.300000e+01,3.200000e+01,1.166227e+06,1.891041e+06,2.010000e+03,4.185670e+01,-8.766547e+01
75%,1.103959e+07,1.731000e+03,1.700000e+01,3.400000e+01,5.600000e+01,1.176406e+06,1.909415e+06,2.017000e+03,4.190711e+01,-8.762806e+01
max,1.417761e+07,2.535000e+03,3.100000e+01,5.000000e+01,7.700000e+01,1.205119e+06,1.951622e+06,2.026000e+03,4.202291e+01,-8.752453e+01

## Check Missing Values

In [10]:
df.isnull().sum()

ID                           0
Case Number                  0
Date                         0
Block                        0
IUCR                         0
Primary Type                 0
Description                  0
Location Description     15930
Arrest                       0
Domestic                     0
Beat                         0
District                    47
Ward                    614815
Community Area          613726
FBI Code                     0
X Coordinate             96443
Y Coordinate             96443
Year                         0
Updated On                   0
Latitude                 96443
Longitude                96443
Location                 96443
dtype: int64

## Sample Records

In [11]:
df_sample = df.sample(n=500000, random_state=42)

print("Sample created ✅")
print(df_sample.shape)

Sample created ✅
(500000, 22)

In [12]:
df_sample.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
7514641,2588748,HJ182614,02/14/2003 06:17:00 AM,014XX W ERIE ST,0460,BATTERY,SIMPLE,ALLEY,False,False,...,27.0,24.0,08B,1166236.0,1904446.0,2003,02/28/2018 03:56:25 PM,41.893379,-87.664923,"(41.893378771, -87.664922545)"
6260639,4376996,HL669179,10/12/2005 05:51:46 PM,002XX W 69TH ST,0460,BATTERY,SIMPLE,SIDEWALK,False,False,...,6.0,69.0,08B,1175998.0,1859224.0,2005,02/28/2018 03:56:25 PM,41.769072,-87.630429,"(41.769071616, -87.630429489)"
1603059,11765740,JC356866,07/20/2019 11:15:00 AM,001XX E 105TH ST,501A,OTHER OFFENSE,ANIMAL ABUSE/NEGLECT,RESIDENCE,False,False,...,9.0,49.0,26,1179045.0,1835359.0,2019,07/31/2019 03:49:01 PM,41.703514,-87.619986,"(41.703514283, -87.619985783)"
201494,13858494,JJ282600,06/05/2025 08:00:00 AM,075XX S WABASH AVE,1150,DECEPTIVE PRACTICE,CREDIT CARD FRAUD,RESIDENCE,False,False,...,6.0,69.0,11,1178022.0,1855082.0,2025,03/14/2026 03:41:39 PM,41.757660,-87.623136,"(41.75765988, -87.623135872)"
3570522,8688341,HV363824,07/02/2012 08:30:00 AM,015XX W GRAND AVE,0610,BURGLARY,FORCIBLE ENTRY,APARTMENT,False,False,...,26.0,24.0,05,1165948.0,1903575.0,2012,02/04/2016 06:33:39 AM,41.890995,-87.666005,"(41.890994834, -87.666005141)"

## Remove Duplicates

In [13]:
before = df_sample.shape[0]

df_sample = df_sample.drop_duplicates()

after = df_sample.shape[0]

print("Duplicates removed:", before - after)

Duplicates removed: 0

## Handle missing values

In [14]:
df_sample = df_sample.dropna(subset=["Date", "Primary Type", "Latitude", "Longitude"])

print("After dropping critical nulls:")
df_sample.isnull().sum()

After dropping critical nulls:

ID                          0
Case Number                 0
Date                        0
Block                       0
IUCR                        0
Primary Type                0
Description                 0
Location Description      633
Arrest                      0
Domestic                    0
Beat                        0
District                    5
Ward                    35891
Community Area          35826
FBI Code                    0
X Coordinate                0
Y Coordinate                0
Year                        0
Updated On                  0
Latitude                    0
Longitude                   0
Location                    0
dtype: int64

#### Drop rows where location is missing

In [15]:
df_sample = df_sample.dropna(subset=["Latitude", "Longitude"])

print("After dropping location nulls:")
df_sample.shape

After dropping location nulls:

(494196, 22)

#### Filling less important missing values

In [16]:
# Location Description → fill with 'UNKNOWN'
df_sample["Location Description"] = df_sample["Location Description"].fillna("UNKNOWN")

In [17]:
# Ward & Community Area → fill with mode (most frequent value)
df_sample["Ward"] = df_sample["Ward"].fillna(df_sample["Ward"].mode()[0])
df_sample["Community Area"] = df_sample["Community Area"].fillna(df_sample["Community Area"].mode()[0])

In [18]:
# District (few missing)
df_sample["District"] = df_sample["District"].fillna(df_sample["District"].mode()[0])

In [19]:
df_sample.isnull().sum()

ID                      0
Case Number             0
Date                    0
Block                   0
IUCR                    0
Primary Type            0
Description             0
Location Description    0
Arrest                  0
Domestic                0
Beat                    0
District                0
Ward                    0
Community Area          0
FBI Code                0
X Coordinate            0
Y Coordinate            0
Year                    0
Updated On              0
Latitude                0
Longitude               0
Location                0
dtype: int64

## Fix Data Types Properly

In [20]:
# Convert Date
df_sample["Date"] = pd.to_datetime(df_sample["Date"], errors="coerce")

In [21]:
# Convert categorical columns
categorical_cols = [
    "Primary Type",
    "Description",
    "Location Description",
    "IUCR",
    "FBI Code"
]

for col in categorical_cols:
    df_sample[col] = df_sample[col].astype("category")

In [22]:
# Convert numeric columns properly
df_sample["District"] = df_sample["District"].astype(int)
df_sample["Ward"] = df_sample["Ward"].astype(int)
df_sample["Community Area"] = df_sample["Community Area"].astype(int)

## Drop Unnecessary Columns

In [23]:
columns_to_drop = [
    "Case Number",
    "Block",
    "IUCR",
    "FBI Code",
    "Updated On",
    "Location"
]

df_sample = df_sample.drop(columns=columns_to_drop)

df_sample.columns

Index(['ID', 'Date', 'Primary Type', 'Description', 'Location Description',
       'Arrest', 'Domestic', 'Beat', 'District', 'Ward', 'Community Area',
       'X Coordinate', 'Y Coordinate', 'Year', 'Latitude', 'Longitude'],
      dtype='object')

## Final Check

In [24]:
df_sample.info()

<class 'pandas.core.frame.DataFrame'>
Index: 494196 entries, 7514641 to 497828
Data columns (total 16 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    494196 non-null  int64
 1   Date                  494196 non-null  datetime64[ns]
 2   Primary Type          494196 non-null  category
 3   Description           494196 non-null  category
 4   Location Description  494196 non-null  category
 5   Arrest                494196 non-null  bool
 6   Domestic              494196 non-null  bool
 7   Beat                  494196 non-null  int64
 8   District              494196 non-null  int64
 9   Ward                  494196 non-null  int64
 10  Community Area        494196 non-null  int64
 11  X Coordinate          494196 non-null  float64
 12  Y Coordinate          494196 non-null  float64
 13  Year                  494196 non-null  int64
 14  Latitude              494196 non-null  float64
 15  Longitude             494196 non-null  float64
dtypes: bool(2), category(3), datetime64[ns](1), float64(4), int64(6)
memory usage: 48.6 MB

In [25]:
df_sample.head()

,ID,Date,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,X Coordinate,Y Coordinate,Year,Latitude,Longitude
7514641,2588748,2003-02-14 06:17:00,BATTERY,SIMPLE,ALLEY,False,False,1324,12,27,24,1166236.0,1904446.0,2003,41.893379,-87.664923
6260639,4376996,2005-10-12 17:51:46,BATTERY,SIMPLE,SIDEWALK,False,False,722,7,6,69,1175998.0,1859224.0,2005,41.769072,-87.630429
1603059,11765740,2019-07-20 11:15:00,OTHER OFFENSE,ANIMAL ABUSE/NEGLECT,RESIDENCE,False,False,512,5,9,49,1179045.0,1835359.0,2019,41.703514,-87.619986
201494,13858494,2025-06-05 08:00:00,DECEPTIVE PRACTICE,CREDIT CARD FRAUD,RESIDENCE,False,False,623,6,6,69,1178022.0,1855082.0,2025,41.757660,-87.623136
3570522,8688341,2012-07-02 08:30:00,BURGLARY,FORCIBLE ENTRY,APARTMENT,False,False,1324,12,26,24,1165948.0,1903575.0,2012,41.890995,-87.666005

## Saving updated CSV

In [ ]:
print("Final check before saving 👇")

print(df_sample.shape)
print(df_sample.isnull().sum())
df_sample.head()

Final check before saving 👇
(494196, 16)
ID                      0
Date                    0
Primary Type            0
Description             0
Location Description    0
Arrest                  0
Domestic                0
Beat                    0
District                0
Ward                    0
Community Area          0
X Coordinate            0
Y Coordinate            0
Year                    0
Latitude                0
Longitude               0
dtype: int64

,ID,Date,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,X Coordinate,Y Coordinate,Year,Latitude,Longitude
7514641,2588748,2003-02-14 06:17:00,BATTERY,SIMPLE,ALLEY,False,False,1324,12,27,24,1166236.0,1904446.0,2003,41.893379,-87.664923
6260639,4376996,2005-10-12 17:51:46,BATTERY,SIMPLE,SIDEWALK,False,False,722,7,6,69,1175998.0,1859224.0,2005,41.769072,-87.630429
1603059,11765740,2019-07-20 11:15:00,OTHER OFFENSE,ANIMAL ABUSE/NEGLECT,RESIDENCE,False,False,512,5,9,49,1179045.0,1835359.0,2019,41.703514,-87.619986
201494,13858494,2025-06-05 08:00:00,DECEPTIVE PRACTICE,CREDIT CARD FRAUD,RESIDENCE,False,False,623,6,6,69,1178022.0,1855082.0,2025,41.757660,-87.623136
3570522,8688341,2012-07-02 08:30:00,BURGLARY,FORCIBLE ENTRY,APARTMENT,False,False,1324,12,26,24,1165948.0,1903575.0,2012,41.890995,-87.666005

In [27]:
output_path = "../datasets/processed_datasets/cleaned_data.csv"

df_sample.to_csv(output_path, index=False)

print("✅ Cleaned dataset saved successfully!")

✅ Cleaned dataset saved successfully!